image: gradle:7.2.0-jdk11

build:
  stage: build
  script: 
    - gradle --build-cache assemble --scan
    - gradle test

test:
  stage: test
  script: gradle check --scan
  only:
    - Release
    - merge_requests
