image: gradle:7.2.0-jdk11

build:
  stage: build
  script: 
    - gradle --build-cache assemble --scan
    - gradle check --scan

test:
  stage: homologacao
  script: gradle test
  only:
    - Release
    - merge_requests
